name: Deploy to Github pages
on:
  push:
    branches:
      - master
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build the project for production
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_PROD }}
        run: npm run build
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.4.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'TheDarkestDay'
          destination-repository-name: 'TheDarkestDay.github.io'
          user-email: alexzund3r@yahoo.com
          target-branch: main
          target-directory: clock
      - run: echo "🍏 This job's status is ${{ job.status }}."